version: "3.7"
services:
  web:
    build: .
    volumes:
      - ./example_app:/var/www/html
    ports:
      - "80:80"
  db:
    image: mysql
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_app
    ports:
      - "3306:3306"
